server:
  port: 8090

spring:
  redis:
    host: 121.199.79.6
    port: 6379
    database: 0
    password: 23d21aca
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0


